spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./fibu
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: validate
#    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
spring.mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER
logging.level.org.springframework.web.servlet.mvc.support: ERROR
